
version: '3'
services:
  mission11:
    image: jupyter/base-notebook
    container_name: mission11-jupyter-notebook
    ports:
      - "9453:8888"
    volumes:
      - ~/jupyter:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
